# Generated by Django 2.1.4 on 2019-01-04 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couplet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text='start with 1')),
                ('content', models.TextField()),
                ('card', models.FileField(upload_to='couplet/')),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text='start with 1')),
                ('content', models.TextField()),
                ('card', models.FileField(upload_to='poem/')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='card',
        ),
        migrations.RemoveField(
            model_name='order',
            name='poem',
        ),
        migrations.AddField(
            model_name='order',
            name='couplet_viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='poem_viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.TextField(choices=[('portrait', 'portrait'), ('landscape', 'landscape')], default='landscape'),
        ),
        migrations.AddField(
            model_name='poem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
        ),
        migrations.AddField(
            model_name='couplet',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
        ),
    ]
