# Generated by Django 2.1.4 on 2019-01-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='couplet',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='couplet_card',
            field=models.FileField(null=True, upload_to='couplet_card/'),
        ),
    ]
