# Generated by Django 2.1.4 on 2018-12-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='images/')),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('poem', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
